project:
  type: website
  output-dir: _site
  render: 
    - index.qmd
    - publications.qmd
    - courses.qmd
    - software.qmd
    - talks.qmd
    - interactive_graphs.qmd
    - software/*
    - courses/*

  resources:    
    - data/
    - downloads/
    - interactive_graphs/

website:
  navbar:
    title: "Paul Lambert"
    left:
      - href: index.qmd
        text: "Home"
      - publications.qmd
      - href: software.qmd
        text: "Software & Tutorials"
      - talks.qmd
      - courses.qmd
      - href: interactive_graphs.qmd
        text: Interactive graphs
        
  sidebar:
    - title: "Software"
      style: "docked"
      background: light
      contents:
        - stpm3.qmd
        - standsurv.qmd
        - stpp.qmd    

  google-analytics:
    tracking-id: "G-JT233ENTVR"
    anonymize-ip: true    
    storage: none        

format:
  html:
    theme: 
      light: minty
      dark: solar    
    css: styles.css
    toc: true
    page-layout: full
    highlight-style: monochrome

execute:
  freeze: auto