project:
  type: website
  output-dir: docs

website:
  navbar:
    title: "Paul Lambert"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - software.qmd
      - talks.qmd
      - href: interactive_graphs.qmd
        text: Interactive graphs

format:
  html:
    theme: 
      light: minty
      dark: solar    
    css: styles.css
    toc: true
    page-layout: full
