---
title: "Courses"
---

When I worked at the University of Leicester my main teaching was on the [MSc Medical Statistics course](https://le.ac.uk/courses/medical-statistics-msc/2024) where I taught various modules including survival analysis, advanced survival analysis, statistical inference and computationally intensive methods. I was a student on this course way back in 1991.

Now my teaching is mainly delivery of specialist courses.

## Upcoming courses

 - June 2025. We (Paul Dickman, Mark Rutherford, Therese Andersson and Betty Syriopoulou and I) will teach our 5-day course on statistical methods for population-based cancer survival analysis in Veneto Italy. Further details are available [here](https://cansurv.net/).
 
## Past (recent) courses
 
 - 27 September 2024. [Modelling survival data using flexible parametric models in Stata using stpm3: concepts and modelling choices](courses/stpm3course.qmd). Internal course at Department of Medical Epidemiology and Biostatistics, Karolinska Institutet, Stockholm, Sweden.

 - 9 September 2024. [Modelling survival data using flexible parametric models in Stata using stpm3: concepts and modelling choices](https://www.kreftregisteret.no/Generelt/kalender/survival-2024/). Pre conference course at the [2024 Northern European Stata Conference](https://www.stata.com/meeting/northern-european24/).
 
 
 