---
title: "`standsurv`"
aliases:
  - standsurv/
---

The `standsurv` command estimates standardized survival curves and related measures. It also allows various contrasts between the standardized functions. It is a post-estimation command and can be used after fitting a wide range of survival models. These include `streg` models (except generalized gamma), `stpm2` models, `stpm3`models and `strcs` models. 

Note that I previously developed `stpm2_standsurv`, which only works with `stpm2` models, but `standsurv` superceeds that. You can do the same things with `standsurv` and much, much more.

So some of the examples are the same as `stpm2_standsurv`. 

You can install `standsurv` within Stata using

```stata
. ssc install standsurv 
```

## Using `standsurv`

### Standard Survival Models
- [Standardized survival functions and contrasts.](/software/standsurv/standardized_survival.qmd)
- [Centiles of the standardized survival function.](/software/standsurv/standardized_survival_centiles.qmd)
- [Restricted mean survival using standardized survival functions.](/software/standsurv/standardized_survival_rmst.qmd)
- [The hazard function of the standardized survival curve.](/software/standsurv/standardized_survival_hazard.qmd)
- [Estimating attributable fractions in cohort studies](/software/standsurv/standardized_survival_AF.qmd)
- [Some comments on why I am not so keen on `stteffects`](/software/standsurv/why_not_stteffects/)
- Why just not use `margins`?

### Competing Risk Models
- [Standardized cause-specific cumulative incidence functions.](/software/standsurv/standardized_cif.qmd)
- Other useful standardized measures in competing risks

### Relative/Net Survival Models 
- [Standardized Relative Survival.](/software/standsurv/standardized_relative_survival.qmd)  
- External age-standardization
- Loss in Expectation of Life
- [Standardized Crude Probabilities of death.](/software/standsurv/standardized_crude_probabilities_of_death.qmd) 

## General
- [Comparing models fitted in different countries](/software/standsurv/models_different_countries.qmd)  

## Releases
See [standsurv_releases.txt](/software/standsurv/standsurv_releases.txt)
