---
title: "`stcrprep`"
---

`stcrprep` prepares data for estimating and modelling cause-specific cumulative incidence functions using time-dependent weights. Once the data has been prepared and the weights incorporated using `stset` it is possible to obtain a graph of the non-parametric estimates of the cause-specific cumulative incidence function using `sts graph`. In addition a model that estimates subhazard ratios (equivalent to the Fine and Gray model) can be fitted using `stcox`. It is also possible to fit parametric models to directly estimate the cause-specific CIF (my main reason for developing the command), for example using `stpm3`.

More details can be found in the [Stata Journal article](https://www.stata-journal.com/article.html?article=st0471)


I should point out that I am less keen on modelling the subhazard than
when I wrote this command. Generally, I prefer to use fit cause-specific
hazard models for each cause and then combine these to estimate the
cause-sepcific CIFs.

Below are some simple examples of using `stcrprep`.

## Examples
### Non and semi parametric methods
 - [Using sts graph for cause-specific CIFs](/software/stcrprep/nonparametriccif.qmd) 
 - [Using stcox instead of stcrreg](/software/stcrprep/stcox_instead_of_stcrreg.qmd)
 - [Computational benefits of using stcrprep](/software/stcrprep/computational_benefits.qmd)
 - Schoenfeld residuals

### Parametric models
 - [Using `stpm3` to model the cause-specific CIF](/software/stcrprep/stpm3_to_model_CIFs.qmd)
 - Alternative link functions.