---
title: "All Publications"
author: "Paul Lambert"
date: "`r Sys.Date()`"
output: md_document
csl: national-institute-of-health-research.csl
categories: []
link-citations: true
bibliography: allrefs.bib
---

---
nocite: |
 @Johansson2024;
 @Lundberg2024;
 @Hall2024;
 @Lee2024;
 @Jennings2023;
 @Leontyeva2023;
 @Waterhouse2023;
 @Booth2023;
 @Tyrer2023;
 @Wells2023;
 @Sweeting2023;
 @Myklebust2023;
 @Teece2023;
 @Skourlis2023;
 @Coles2023;
 @Lundberg2022a;
 @Batyrbekova2022;
 @Syriopoulou2022a;
 @Leontyeva2022;
 @Syriopoulou2022;
 @Schmidt2022;
 @Lundberg2022;
 @Bower2022;
 @Smith2022;
 @Stannard2022;
 @Skourlis2022;
 @Andersson2022b;
 @Leontyeva2022;
 @Andersson2022a;
 @Rutherford2022;
 @Andersson2022;
 @Lee2022;
 @Riley2021;
 @Skourlis2021;
 @Syriopoulou2021a;
 @Sweeting2021;
 @Coles2021;
 @Lambert2021;
 @Mozumder2021;
 @Ensor2021;
 @Hill2021;
 @Weibull2021;
 @Andersson2021;
 @TSD21;
 @Andersson2021a;
 @Syriopoulou2021;
 @Smith2020;
 @Lundberg2020;
 @Lambert2020;
 @Myklebust2020;
 @Rutherford2020;
 @Welch2020;
 @Booth2020;
 @Syriopoulou2020;
 @Arnold2019;
 @Wong2019;
 @Andersson2019;
 @Bower2019a;
 @Syriopoulou2019;
 @Rutherford2019;
 @Bower2019;
 @Weibull2019;
 @Syriopoulou2018;
 @Plym2018;
 @Mozumder2018;
 @Weibull2018;
 @Latimer2018;
 @Mozumder2017;
 @Mozumder2016;
 @Bower2017;
 @Latimer2017;
 @Peters2017;
 @Crowther2016a;
 @Cramb2016;
 @Lambert2016a;
 @Lambert2016;
 @Syriopoulou2017;
 @Bower2016a;
 @Bower2016b;
 @Bower2016c;
 @Edgren2016;
 @Crowther2016;
 @Andersson2015;
 @Hultcrantz2015;
 @Rutherford2015d;
 @Rutherford2015c;
 @Crowther2015;
 @Lambert2015;
 @Rutherford2015b;
 @Rutherford2013c;
 @Crowther2014;
 @Eloranta2014;
 @Feldman2014;
 @Gao2014;
 @Latimer2014;
 @Andersson2014;
 @Andersson2013;
 @Ahyow2013;
 @Crowther2013a;
 @Crowther2013;
 @Crowther2013c;
 @Crowther2013b;
 @Cvancarova2013;
 @Eloranta2013;
 @Eloranta2013a;
 @Hinchliffe2013b;
 @Hinchliffe2013;
 @Hinchliffe2013d;
 @Hinchliffe2013e;
 @Hinchliffe2013a;
 @Rutherford2013b;
 @Rutherford2013a;
 @Dickman2013;
 @Shah2013;
 @Yu2013;
 @Andersson2012;
 @Andrae2012;
 @Crowther2012;
 @Crowther2012b;
 @Crowther2012a;
 @Eloranta2012;
 @Hinchliffe2012;
 @Hinchliffe2012a;
 @Holmberg2012;
 @Moeller2012;
 @Rutherford2012;
 @Rutherford2012a;
 @Shack2012;
 @Andersson2011;
 @Eaker2011;
 @Hakulinen2011;
 @Lambert2011;
 @Coleman2011a;
 @Morden2011;
 @Morris2011;
 @Andersson2010;
 @Eloranta2010;
 @Lambert2010a;
 @Lambert2010;
 @Riley2010;
 @Rutherford2010;
 @Squire2010;
 @Lambert2009;
 @Larfors2009;
 @Panickar2009;
 @Woods2009;
 @Bhaskaran2008;
 @Gillies2008;
 @Lambert2008a;
 @Nelson2008;
 @Lambert2008;
 @Reynolds2008;
 @Riley2008;
 @Cooper2007;
 @Gillies2007;
 @Lambert2007b;
 @Lambert2007;
 @Lambert2007a;
 @Manca2007;
 @Nelson2007;
 @Riley2007a;
 @Riley2007;
 @Sutton2007;
 @Abrams2005;
 @Lambert2005;
 @Lambert2005a;
 @Minelli2005;
 @Sutton2005;
 @Taub2005;
 @Lambert2004;
 @Riley2004a;
 @Riley2004;
 @Smith2004;
 @Sweeting2004;
 @Baker2003;
 @Hsu2003;
 @Mckean2003;
 @Oommen2003;
 @Baker2003;
 @Riley2003;
 @Cooper2003;
 @Riley2003a;
 @Waugh2003b;
 @Riley2003b;
 @Smith2003;
 @Waugh2003;
 @Lambert2002;
 @Young2002;
 @Sutton2002;
 @Lambert2001;
 @Mckean2001;
 @Waugh2000;
 @Bell1999;
 @Williams1999;
 @Brooke1998;
 @Hellmich1998;
 @Penny1998;
 @Halligan1997;
 @Brooke1996;
 @Halligan1996;
 @Halligan1996a;
 @Peek1996;
 @Luyt1995;
 @Brooke1995;
 @Esmail1995


